language: objective-c
osx_image: xcode11.1
jobs:
  include:
    - stage: Swift PM
      osx_image: xcode11.4
      script:
      # Build the project using Swift PM
        - swift build
      # Test the project using Swift PM
        - swift test

    - stage: Xcode Tests
      env:
        - MODE=OSX CFG=Debug
        - MODE=OSX CFG=Release
        - MODE=iOS CFG=Debug
        - MODE=iOS CFG=Release
        - MODE=tvOS CFG=Debug
        - MODE=tvOS CFG=Release
        - MODE=watchOS CFG=Debug
        - MODE=watchOS CFG=Release
      script:
        - ./.travis.sh "${MODE}" "${CFG}"
      notifications:
        email: false

      branches:
        except:
          - google
