name: CocoaPods

on:
  push:
    branches: [ main, 2_2_branch ]
    paths:
    - 'Sources/**'
    - 'UnitTests/**'
    - '*.podspec'
    - '.github/workflows/cocoapods.yml'
  pull_request:
    branches: [ main, 2_2_branch ]
    paths:
    - 'Sources/**'
    - 'UnitTests/**'
    - '*.podspec'
    - '.github/workflows/cocoapods.yml'
  # Also allow manual triggering from the github UX to revalidate things.
  workflow_dispatch:

jobs:
  pod-lib-lint:
    # TODO: back to `macos-latest` once that is updated to point to the newer
    # images for more current Xcode versions.
    #  https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    #  https://github.com/actions/runner-images/issues/6384
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        # Add back watchOS. See CocoaPods/CocoaPods#11558
        PLATFORM: ["ios", "macos", "tvos"]
        CONFIGURATION: ["Debug", "Release"]
    steps:
    - uses: actions/checkout@v3
    # Manually expanding out static frameworks to avoid making to many jobs.
    - name: Pod lib lint
      run:  |
        pod lib lint --verbose \
          --configuration=${{ matrix.CONFIGURATION }} \
          --platforms=${{ matrix.PLATFORM }} \
          GTMSessionFetcher.podspec
    - name: Pod lib lint - Use Static Frameworks
      run:  |
        pod lib lint --verbose --use-static-frameworks \
          --configuration=${{ matrix.CONFIGURATION }} \
          --platforms=${{ matrix.PLATFORM }} \
          GTMSessionFetcher.podspec
