name: SwiftPM

on:
  push:
    branches: [ main, 2_2_branch ]
    paths:
    - 'Sources/**'
    - 'SwiftPMTests/**'
    - 'UnitTests/**'
    - 'Package*.swift'
    - '.github/workflows/swiftpm.yml'
  pull_request:
    branches: [ main, 2_2_branch ]
    paths:
    - 'Sources/**'
    - 'SwiftPMTests/**'
    - 'UnitTests/**'
    - 'Package*.swift'
    - '.github/workflows/swiftpm.yml'
  # Also allow manual triggering from the github UX to revalidate things.
  workflow_dispatch:

jobs:
  swift:
    # The swift command line only support build/testing for macOS on.

    # TODO: back to `macos-latest` once that is updated to point to the newer
    # images for more current Xcode versions.
    #  https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    #  https://github.com/actions/runner-images/issues/6384
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        CONFIGURATION: ["debug", "release"]
    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run:  |
        set -eu
        swift build --configuration ${{ matrix.CONFIGURATION }}
        swift test --configuration ${{ matrix.CONFIGURATION }}

  xcodebuild:
    # Job(s) to build for all the platforms to ensure that is working and the
    # tests are passing.

    # TODO: back to `macos-latest` once that is updated to point to the newer
    # images for more current Xcode versions.
    #  https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        PLATFORM: ["ios", "macos", "tvos", "watchos"]
        CONFIGURATION: ["Debug", "Release"]
    steps:
    - uses: actions/checkout@v3
    - name: Build and Test
      run:  |
        set -eu
        case "${{matrix.PLATFORM}}" in
          ios)
            DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=latest"
            ;;
          macos)
            DESTINATION="platform=macOS"
            ;;
          tvos)
            DESTINATION="platform=tvOS Simulator,name=Apple TV,OS=latest"
            ;;
          watchos)
            DESTINATION="platform=WatchOS Simulator,name=Apple Watch Series 7 (45mm),OS=latest"
            ;;
        esac

        set -o pipefail
        xcodebuild \
            -scheme GTMSessionFetcher-Package \
            -configuration ${{ matrix.CONFIGURATION }} \
            -destination "${DESTINATION}" \
            build test \
          | xcpretty
