name: TestApps

on:
  push:
    branches: [ main ]
    paths:
    - 'Sources/**'
    - 'TestApps/**'
    - '.github/workflows/test_apps.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'Sources/**'
    - 'TestApps/**'
    - '.github/workflows/test_apps.yml'

jobs:
  xcodebuild:
    # TODO: back to `macos-latest` once that is updated to point to the newer
    # images for more current Xcode versions.
    #  https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        # iOS runs into codesigning requirements to build applications, haven't
        # found a good way to suppress that and just ensure things build.
        #PLATFORM: ["iOS", "macOS"]
        PLATFORM: ["macOS"]
        CONFIGURATION: ["Debug", "Release"]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run:  |
        set -eu
        case "${{matrix.PLATFORM}}" in
          iOS)
            XCODE_SCHEME="iOSTestApp"
            ;;
          macOS)
            XCODE_SCHEME="OSXTestApp"
            ;;
        esac

        set -o pipefail
        xcodebuild \
            -project TestApps/TestApps.xcodeproj \
            -scheme "${XCODE_SCHEME}" \
            -configuration ${{ matrix.CONFIGURATION }} \
            build \
          | xcpretty
